version: '3'
services:
  dashboard:
    build:
      context: . 
    user: root
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: streamlit run src/main.py
